version: 2.1

################# ORB #################
orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.4.0

################# WORKFLOWS #################
workflows:
  build_and_test:
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows 
    jobs:
      - build-and-code-check
      - tests-no-kafka:
          requires:
            - build-and-code-check
      - tests:
          requires:
            - build-and-code-check
      - check-repo:
          requires:
            - build-and-code-check
            - tests-no-kafka
            - tests

################# JOBS #################
jobs:
  # Build the repo and check the code using pyflakes 
  build-and-code-check:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: pip install
          command: cd ~/project; pip install .[all]; cd -
      - run:
          name: code check
          command: cd ~/project; python -m pyflakes .; cd -
      - persist_to_workspace:
          root: .
          paths:
            - .
  # Run unittests that don't interact with the kafka cluster at all in parallel
  tests-no-kafka:
    docker:
      - image: cimg/python:3.7
    parallelism: 3
    steps:
      - attach_workspace:
          at: .
      - run:
          name: run non-Kafka tests
          command: |
            echo 'cwd = ' $(pwd)
            echo 'cwd ls = ' $(ls)
            echo 'glob output = ' $(circleci tests glob "test/unittests/test*parallel.py")
            circleci tests glob "test/unittests/test*parallel.py" | xargs -n 1 echo
            echo 'glob + sed = ' $(circleci tests glob "test/unittests/test*parallel.py" | sed -r 's/\//./g' | sed -e 's/.py//')
            circleci tests glob "test/unittests/test*parallel.py" | sed -r 's/\//./g' | sed -e 's/.py//' | xargs -n 1 echo
            TESTCLASSES=$(circleci tests glob "test/unittests/test*parallel.py" | sed -r 's/\//./g' | sed -e 's/.py//' | circleci tests split)
            echo 'TESTCLASSES = ' $TESTCLASSES
            python -m unittest $TESTCLASSES
      - persist_to_workspace:
          root: .
          paths:
              - .
  # Run unittests that DO interact with the kafka cluster sequentially
  tests:
    docker:
      - image: cimg/python:3.7
    steps:
      - attach_workspace:
          at: .
      - run:
          name: test datafilechunk
          command: cd test/unittests; python -m unittest testdatafilechunk
      - run:
          name: test datafile
          command: cd test/unittests; python -m unittest testdatafile
  # Make sure that the repository is clean after all tests have been run
  check-repo:
    docker:
      - image: cimg/python:3.7
    steps:
      - attach_workspace:
          at: .
      - run:
          name: check repo
          command: cd ~/project; sh test/test_repo_status.sh
